# BEGIN THEME-SYNC
wallpaper: boot():/limine/wallpaper.jpg
wallpaper_style: stretched

interface_branding: ArunOS
interface_branding_colour: cac1ed

interface_help_colour: cac1ed

term_background: CC0f0e12
term_foreground: e9e3ef

backdrop: 0f0e12
# END THEME-SYNC

TIMEOUT=5
DEFAULT_ENTRY=0

/Arch
    //Server
        PROTOCOL: linux
        KERNEL_PATH: boot():/vmlinuz-linux
        MODULE_PATH: boot():/intel-ucode.img
        MODULE_PATH: boot():/initramfs-linux.img
        CMDLINE: root=UUID=ac1be9d9-7f22-4b81-bb3e-c32202e4ff14 rw rootfstype=btrfs systemd.unit=multi-user.target

    //Desktop
        PROTOCOL: linux
        KERNEL_PATH: boot():/vmlinuz-linux
        MODULE_PATH: boot():/intel-ucode.img
        MODULE_PATH: boot():/initramfs-linux.img
        CMDLINE: root=UUID=ac1be9d9-7f22-4b81-bb3e-c32202e4ff14 rw rootfstype=btrfs quiet splash systemd.unit=graphical.target

/Windows
    PROTOCOL: efi_chainload
    IMAGE_PATH: e16087fb-9faa-417f-80a0-799867cbd4e5:/EFI/Microsoft/Boot/bootmgfw.efi
