$background = 0f0e12
$onBackground = e9e3ef
$surface = 0f0e12
$surfaceDim = 0f0e12
$surfaceBright = 2d2b34
$surfaceContainerLowest = 000000
$surfaceContainerLow = 141318
$surfaceContainer = 1a191f
$surfaceContainerHigh = 201f26
$surfaceContainerHighest = 27252d
$onSurface = e9e3ef
$surfaceVariant = 27252d
$onSurfaceVariant = aea9b5
$outline = 77747e
$outlineVariant = 494650
$inverseSurface = fdf8fe
$inverseOnSurface = 565459
$shadow = 000000
$scrim = 000000
$surfaceTint = cac1ed
$primary = cac1ed
$primaryDim = bcb3df
$onPrimary = 423b60
$primaryContainer = 554d73
$onPrimaryContainer = e7dfff
$inversePrimary = 615a80
$primaryFixed = d6ccf9
$primaryFixedDim = c8beea
$onPrimaryFixed = 362f53
$onPrimaryFixedVariant = 534c71
$secondary = cac3dc
$secondaryDim = bcb5ce
$onSecondary = 423d52
$secondaryContainer = 3d394d
$onSecondaryContainer = c2bcd5
$secondaryFixed = e6dff9
$secondaryFixedDim = d8d1ea
$onSecondaryFixed = 413d51
$onSecondaryFixedVariant = 5d596e
$tertiary = ffdff6
$tertiaryDim = fdcbf2
$onTertiary = 6f4969
$tertiaryContainer = fdcbf2
$onTertiaryContainer = 654060
$tertiaryFixed = fdcbf2
$tertiaryFixedDim = eebde3
$onTertiaryFixed = 512e4c
$onTertiaryFixedVariant = 704a6a
$error = f97386
$errorDim = c44b5f
$onError = 490013
$errorContainer = 871c34
$onErrorContainer = ff97a3
$primaryPaletteKeyColor = 7a729a
$secondaryPaletteKeyColor = 79748a
$tertiaryPaletteKeyColor = 936a8c
$neutralPaletteKeyColor = 79767c
$neutralVariantPaletteKeyColor = 797580
$errorPaletteKeyColor = c74d61
$primary_paletteKeyColor = 7a729a
$secondary_paletteKeyColor = 79748a
$tertiary_paletteKeyColor = 936a8c
$neutral_paletteKeyColor = 79767c
$neutral_variant_paletteKeyColor = 797580
$term0 = 353434
$term1 = bd6aff
$term2 = ffbac2
$term3 = ffdcf2
$term4 = 9fa8d8
$term5 = bc9ce7
$term6 = 9dceff
$term7 = e8d3de
$term8 = ac9fa9
$term9 = ce8dff
$term10 = ffd2d5
$term11 = fff0f6
$term12 = b8c0dd
$term13 = d1b3f1
$term14 = bae0ff
$term15 = ffffff
$rosewater = f8eff8
$flamingo = ebddf2
$pink = e7d6ff
$mauve = c8b5ff
$red = cba2f9
$maroon = cfb3ea
$peach = e7c0f5
$yellow = ffecf3
$green = c8e3ff
$teal = d7deff
$sky = d4d9ff
$sapphire = bec3ff
$blue = b9b5ff
$lavender = cec6ff
$klink = 7d7fd1
$klinkSelection = 7d7fd1
$kvisited = 8c6fd7
$kvisitedSelection = 8d6ed6
$knegative = ae62f9
$knegativeSelection = af61f8
$kneutral = d68cff
$kneutralSelection = d78cff
$kpositive = 60adff
$kpositiveSelection = 60adff
$text = e9e3ef
$subtext1 = aea9b5
$subtext0 = 77747e
$overlay2 = 68656e
$overlay1 = 59565e
$overlay0 = 4a484f
$surface2 = 3c3a41
$surface1 = 2e2c32
$surface0 = 1e1d22
$base = 0f0e12
$mantle = 0f0e12
$crust = 0e0d11
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
