#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 1 ]]; then
    echo "Usage: wall-build <video>"
    exit 1
fi

VIDEO="$(realpath "$1")"

if [[ ! -f "$VIDEO" ]]; then
    echo "File not found: $VIDEO"
    exit 1
fi

NAME="$(basename "$VIDEO")"
NAME="${NAME%.*}"

PACKAGE="${NAME}.wall"

mkdir -p "$PACKAGE"
mkdir -p "$PACKAGE/frames"

cp "$VIDEO" "$PACKAGE/source.mp4"

cat > "$PACKAGE/metadata.json" <<EOF
{
  "type": "animated",
  "fps": 12,
  "loop": true,
  "theme_source": "preview.jpg"
}
EOF

echo "[*] Generating preview"


DURATION=$(
    ffprobe \
    -v error \
    -show_entries format=duration \
    -of default=noprint_wrappers=1:nokey=1 \
    "$VIDEO"
)

MIDPOINT=$(awk "BEGIN { print $DURATION / 2 }")

ffmpeg \
    -ss "$MIDPOINT" \
    -i "$VIDEO" \
    -frames:v 1 \
    -q:v 2 \
    "$PACKAGE/preview.jpg" \
    -y \
    -loglevel error

echo "[*] Extracting frames"

ffmpeg \
    -i "$VIDEO" \
    -vf fps=12 \
    "$PACKAGE/frames/%04d.jpg" \
    -y \
    -loglevel error

echo "[✓] Created $PACKAGE"


