#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 1 ]]; then
    echo "Usage: wall-info <package.wall>"
    exit 1
fi

PACKAGE="$1"

if [[ ! -d "$PACKAGE" ]]; then
    echo "Package not found: $PACKAGE"
    exit 1
fi

[[ -f "$PACKAGE/metadata.json" ]] || {
    echo "Error: metadata.json doesnt exist, rebuild"
    exit 1
}


TYPE=$(jq -r '.type' "$PACKAGE/metadata.json")

echo "Package: $(basename "$PACKAGE")"
echo
echo "Type: $TYPE"

[[ -f "$PACKAGE/preview.jpg" ]] \
    && echo "Preview: yes" \
    || echo "Preview: no"

[[ -f "$PACKAGE/source.mp4" ]] \
    && echo "Source: yes" \
    || echo "Source: no"
