$background = 0e0e12
$onBackground = e7e4f0
$surface = 0e0e12
$surfaceDim = 0e0e12
$surfaceBright = 2c2b34
$surfaceContainerLowest = 000000
$surfaceContainerLow = 131318
$surfaceContainer = 191920
$surfaceContainerHigh = 1f1f26
$surfaceContainerHighest = 25252e
$onSurface = e7e4f0
$surfaceVariant = 25252e
$onSurfaceVariant = acaab5
$outline = 76747f
$outlineVariant = 484750
$inverseSurface = fcf8fe
$inverseOnSurface = 55545a
$shadow = 000000
$scrim = 000000
$surfaceTint = c3c3ee
$primary = c3c3ee
$primaryDim = b5b5e0
$onPrimary = 3c3d61
$primaryContainer = 4e4f74
$onPrimaryContainer = e2e0ff
$inversePrimary = 5b5c81
$primaryFixed = cecefa
$primaryFixedDim = c0c0eb
$onPrimaryFixed = 303154
$onPrimaryFixedVariant = 4c4d72
$secondary = c6c4dd
$secondaryDim = b8b6cf
$onSecondary = 3e3e52
$secondaryContainer = 393a4d
$onSecondaryContainer = bebdd5
$secondaryFixed = e2e0f9
$secondaryFixedDim = d4d2eb
$onSecondaryFixed = 3d3e51
$onSecondaryFixedVariant = 5a5a6f
$tertiary = fedeff
$tertiaryDim = f5cdf9
$onTertiary = 694a6f
$tertiaryContainer = f5cdf9
$onTertiaryContainer = 604266
$tertiaryFixed = f5cdf9
$tertiaryFixedDim = e7bfea
$onTertiaryFixed = 4c2f52
$onTertiaryFixedVariant = 6a4b70
$error = f97386
$errorDim = c44b5f
$onError = 490013
$errorContainer = 871c34
$onErrorContainer = ff97a3
$primaryPaletteKeyColor = 73749b
$secondaryPaletteKeyColor = 76758b
$tertiaryPaletteKeyColor = 8d6c92
$neutralPaletteKeyColor = 78767c
$neutralVariantPaletteKeyColor = 777680
$errorPaletteKeyColor = c74d61
$primary_paletteKeyColor = 73749b
$secondary_paletteKeyColor = 76758b
$tertiary_paletteKeyColor = 8d6c92
$neutral_paletteKeyColor = 78767c
$neutral_variant_paletteKeyColor = 777680
$term0 = 353434
$term1 = a974ff
$term2 = 44def5
$term3 = ffdcf2
$term4 = 98aad7
$term5 = b29feb
$term6 = 9dceff
$term7 = e8d3de
$term8 = ac9fa9
$term9 = be95ff
$term10 = 89ecff
$term11 = fff0f6
$term12 = b4c1dc
$term13 = c8b5f5
$term14 = bae0ff
$term15 = ffffff
$rosewater = f7eff9
$flamingo = e8def3
$pink = e1d8ff
$mauve = beb9ff
$red = bfa6fe
$maroon = c8b6ed
$peach = e0c2f9
$yellow = ffecf3
$green = c8e3ff
$teal = d3e0ff
$sky = cfdaff
$sapphire = b6c5ff
$blue = afb8ff
$lavender = c6c8ff
$klink = 7182d2
$klinkSelection = 7182d2
$kvisited = 7f73db
$kvisitedSelection = 7f72da
$knegative = 9e69ff
$knegativeSelection = 9e68ff
$kneutral = c794ff
$kneutralSelection = c793ff
$kpositive = 60adff
$kpositiveSelection = 60adff
$text = e7e4f0
$subtext1 = acaab5
$subtext0 = 76747f
$overlay2 = 67656f
$overlay1 = 58565f
$overlay0 = 494850
$surface2 = 3b3a41
$surface1 = 2d2c32
$surface0 = 1d1d22
$base = 0e0e12
$mantle = 0e0e12
$crust = 0d0d11
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
