$background = 0e0e12
$onBackground = e8e3f0
$surface = 0e0e12
$surfaceDim = 0e0e12
$surfaceBright = 2c2b34
$surfaceContainerLowest = 000000
$surfaceContainerLow = 131318
$surfaceContainer = 1a191f
$surfaceContainerHigh = 201f26
$surfaceContainerHighest = 26252d
$onSurface = e8e3f0
$surfaceVariant = 26252d
$onSurfaceVariant = ada9b5
$outline = 76747f
$outlineVariant = 484750
$inverseSurface = fcf8fe
$inverseOnSurface = 565459
$shadow = 000000
$scrim = 000000
$surfaceTint = c7c2ee
$primary = c7c2ee
$primaryDim = b9b4df
$onPrimary = 3f3c60
$primaryContainer = 514e74
$onPrimaryContainer = e5e0ff
$inversePrimary = 5e5b81
$primaryFixed = d8d2ff
$primaryFixedDim = cac4f1
$onPrimaryFixed = 373458
$onPrimaryFixedVariant = 535076
$secondary = c8c3dc
$secondaryDim = bab6ce
$onSecondary = 403e52
$secondaryContainer = 3b394d
$onSecondaryContainer = c0bcd5
$secondaryFixed = e4dff9
$secondaryFixedDim = d6d1eb
$onSecondaryFixed = 3f3d51
$onSecondaryFixedVariant = 5c596e
$tertiary = ffdafa
$tertiaryDim = f6c9f3
$onTertiary = 6a486a
$tertiaryContainer = f6c9f3
$onTertiaryContainer = 613f61
$tertiaryFixed = f6c9f3
$tertiaryFixedDim = e8bce4
$onTertiaryFixed = 4d2d4d
$onTertiaryFixedVariant = 6b496b
$error = f97386
$errorDim = c44b5f
$onError = 490013
$errorContainer = 871c34
$onErrorContainer = ff97a3
$primaryPaletteKeyColor = 77739b
$secondaryPaletteKeyColor = 77748a
$tertiaryPaletteKeyColor = 916b8f
$neutralPaletteKeyColor = 78767c
$neutralVariantPaletteKeyColor = 787680
$errorPaletteKeyColor = c74d61
$primary_paletteKeyColor = 77739b
$secondary_paletteKeyColor = 77748a
$tertiary_paletteKeyColor = 916b8f
$neutral_paletteKeyColor = 78767c
$neutral_variant_paletteKeyColor = 787680
$term0 = 353434
$term1 = b46fff
$term2 = 44def5
$term3 = ffdcf2
$term4 = 9ca9d8
$term5 = b89de9
$term6 = 9dceff
$term7 = e8d3de
$term8 = ac9fa9
$term9 = c691ff
$term10 = 89ecff
$term11 = fff0f6
$term12 = b6c1dd
$term13 = cdb4f3
$term14 = bae0ff
$term15 = ffffff
$rosewater = f8eff8
$flamingo = eaddf3
$pink = e4d7ff
$mauve = c3b7ff
$red = c6a4fb
$maroon = ccb4ec
$peach = e3c1f7
$yellow = ffecf3
$green = c8e3ff
$teal = d5dfff
$sky = d2d9ff
$sapphire = bbc4ff
$blue = b4b6ff
$lavender = cac7ff
$klink = 7781d2
$klinkSelection = 7781d2
$kvisited = 8670d9
$kvisitedSelection = 8670d9
$knegative = a864fe
$knegativeSelection = a764fe
$kneutral = cf90ff
$kneutralSelection = cf90ff
$kpositive = 60adff
$kpositiveSelection = 60adff
$text = e8e3f0
$subtext1 = ada9b5
$subtext0 = 76747f
$overlay2 = 67656f
$overlay1 = 58565f
$overlay0 = 494850
$surface2 = 3b3a41
$surface1 = 2d2c32
$surface0 = 1d1d22
$base = 0e0e12
$mantle = 0e0e12
$crust = 0d0d11
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
