$background = 0c0e12
$onBackground = e1e6ee
$surface = 0c0e12
$surfaceDim = 0c0e12
$surfaceBright = 272d33
$surfaceContainerLowest = 000000
$surfaceContainerLow = 101418
$surfaceContainer = 161a1f
$surfaceContainerHigh = 1b2025
$surfaceContainerHighest = 21262d
$onSurface = e1e6ee
$surfaceVariant = 21262d
$onSurfaceVariant = a6abb4
$outline = 70767e
$outlineVariant = 43484f
$inverseSurface = f8f9fe
$inverseOnSurface = 535559
$shadow = 000000
$scrim = 000000
$surfaceTint = accaea
$primary = accaea
$primaryDim = 9ebcdb
$onPrimary = 24435d
$primaryContainer = 385570
$onPrimaryContainer = cfe6ff
$inversePrimary = 44627e
$primaryFixed = bcdafb
$primaryFixedDim = aecced
$onPrimaryFixed = 1b3a54
$onPrimaryFixedVariant = 3a5772
$secondary = b9c8da
$secondaryDim = abbacc
$onSecondary = 334250
$secondaryContainer = 2f3d4b
$onSecondaryContainer = b2c1d3
$secondaryFixed = d5e4f7
$secondaryFixedDim = c7d6e8
$onSecondaryFixed = 32414f
$onSecondaryFixedVariant = 4f5d6c
$tertiary = d4cfff
$tertiaryDim = c5c2f2
$onTertiary = 47456d
$tertiaryContainer = c5c2f2
$onTertiaryContainer = 3e3c63
$tertiaryFixed = c5c2f2
$tertiaryFixedDim = b8b4e3
$onTertiaryFixed = 2a284e
$onTertiaryFixedVariant = 47456d
$error = fa746f
$errorDim = c54d4a
$onError = 490006
$errorContainer = 871f21
$onErrorContainer = ff9993
$primaryPaletteKeyColor = 5d7a97
$secondaryPaletteKeyColor = 6a7989
$tertiaryPaletteKeyColor = 76739e
$neutralPaletteKeyColor = 75777b
$neutralVariantPaletteKeyColor = 727880
$errorPaletteKeyColor = c84f4c
$primary_paletteKeyColor = 5d7a97
$secondary_paletteKeyColor = 6a7989
$tertiary_paletteKeyColor = 76739e
$neutral_paletteKeyColor = 75777b
$neutral_variant_paletteKeyColor = 727880
$term0 = 343434
$term1 = 8383ff
$term2 = 44def5
$term3 = 75fcdd
$term4 = 83b0cf
$term5 = 8fa9ee
$term6 = 8cd3f3
$term7 = ccdcd6
$term8 = 9aa59f
$term9 = a29eff
$term10 = 89ecff
$term11 = c9fff3
$term12 = a9c5d6
$term13 = abbdf8
$term14 = a8e4ff
$term15 = ffffff
$rosewater = f4f0fa
$flamingo = dfe0f5
$pink = d0ddff
$mauve = 9cc2ff
$red = 97b1ff
$maroon = aebdf1
$peach = e0c2f9
$yellow = d0f9f4
$green = b6e7ff
$teal = bee5ff
$sky = b9e0ff
$sapphire = 92cdff
$blue = 86c1ff
$lavender = abcfff
$klink = 408dc8
$klinkSelection = 408dc8
$kvisited = 4280da
$kvisitedSelection = 4280da
$knegative = 607eff
$knegativeSelection = 607eff
$kneutral = c794ff
$kneutralSelection = c794ff
$kpositive = 00b7ea
$kpositiveSelection = 00b7ea
$text = e1e6ee
$subtext1 = a6abb4
$subtext0 = 70767e
$overlay2 = 62676e
$overlay1 = 53585e
$overlay0 = 45494f
$surface2 = 383b41
$surface1 = 2a2d32
$surface0 = 1b1d22
$base = 0c0e12
$mantle = 0c0e12
$crust = 0b0d11
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
