general {
    hide_cursor = true
}

background {
    path = /home/arun/Pictures/Wallpapers/c1.jpg
    blur_passes = 4
    blur_size = 8
}

label {
    text = cmd[update:1000] date +"%H:%M"
    color = rgb(ffffff)
    font_size = 96

    position = 0, 180
    halign = center
    valign = center
}

label {
    text = cmd[update:1000] date +"%A, %d %B"
    color = rgb(cfcfcf)
    font_size = 22

    position = 0, 110
    halign = center
    valign = center
}

input-field {
    size = 320, 60

    outer_color = rgb(c77dff)
    inner_color = rgba(20,20,30,0.8)
    font_color = rgb(ffffff)

    check_color = rgb(c77dff)
    fail_color = rgb(ff5555)

    outline_thickness = 3

    fade_on_empty = false

    placeholder_text = Password...

    position = 0, -100
    halign = center
    valign = center
}
